name: Build Fyne App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.25

      - name: Install Fyne CLI
        run: go install fyne.io/fyne/v2/cmd/fyne@latest

      - name: Build Linux binary
        run: go build -o chat-app ./cmd/chat

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: chat-app-linux
          path: chat-app

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.25

      - name: Install Fyne CLI
        run: go install fyne.io/fyne/v2/cmd/fyne@latest

      - name: Build Windows binary
        run: go build -o chat-app.exe ./cmd/chat

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: chat-app-windows
          path: chat-app.exe
