name: Build Fyne App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, windows]
        arch: [amd64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.25

    - name: Install Fyne CLI
      run: go install fyne.io/fyne/v2/cmd/fyne@latest

    - name: Build Linux binary
      if: matrix.os == 'linux'
      run: GOOS=linux GOARCH=${{ matrix.arch }} go build -o chat-app ./cmd/chat

    - name: Build Windows binary
      if: matrix.os == 'windows'
      run: GOOS=windows GOARCH=${{ matrix.arch }} go build -o chat-app.exe ./cmd/chat

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: chat-app-${{ matrix.os }}
        path: |
          chat-app
          chat-app.exe
